apiVersion: v1
kind: Namespace
metadata: { name: finops-demo }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: finops-observer, namespace: finops-demo }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: finops-actor, namespace: finops-demo }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: finops-observer-read, namespace: finops-demo }
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: finops-actor-patch, namespace: finops-demo }
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["waster"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: finops-observer-binding, namespace: finops-demo }
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: Role, name: finops-observer-read }
subjects: [{ kind: ServiceAccount, name: finops-observer, namespace: finops-demo }]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: finops-actor-binding, namespace: finops-demo }
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: Role, name: finops-actor-patch }
subjects: [{ kind: ServiceAccount, name: finops-actor, namespace: finops-demo }]
