"""Approval server — bridges Slack Approve/Deny buttons to AAP workflow approvals.

The AAP workflow handles notification (notify-slack.yml with buttons) and
remediation. This server only handles Slack button clicks and bridges them
to AAP's workflow approval API.

Endpoints:
  POST /intent        — receives proposed intents from the Observer, forwards to AAP Event Stream
  POST /slack/events  — Slack Bolt handles interactive button clicks
  GET  /health        — readiness probe

When AAP is configured (AAP_API_URL set):
  Approve → finds pending AAP approval node, calls approve API
  Deny    → finds pending AAP approval node, calls deny API + suppresses workload

When AAP is NOT configured (standalone ROSA fallback):
  Approve → creates Actor K8s Job directly
  Deny    → suppresses workload via K8s annotation
"""
from __future__ import annotations

import json
import logging
import os
import re
from datetime import datetime, timezone, timedelta

import httpx
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler

load_dotenv()

logging.basicConfig(level=logging.INFO, format="[approval] %(message)s")
log = logging.getLogger("approval")

SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_SIGNING_SECRET = os.environ.get("SLACK_SIGNING_SECRET", "")
SLACK_WEBHOOK_URL = os.environ.get("SLACK_WEBHOOK_URL", "")
AAP_API_URL = os.environ.get("AAP_API_URL", "")
AAP_API_TOKEN = os.environ.get("AAP_API_TOKEN", "")
AAP_EVENT_STREAM_URL = os.environ.get("AAP_EVENT_STREAM_URL", "")
AAP_EVENT_STREAM_USER = os.environ.get("EDA_WEBHOOK_USER", "")
AAP_EVENT_STREAM_PASS = os.environ.get("EDA_WEBHOOK_PASSWORD", "")
ACTOR_IMAGE = os.environ.get("ACTOR_IMAGE", "quay.io/pm_ronahuan/finops-actor:latest")
ACTOR_JOB_NAMESPACE = os.environ.get("ACTOR_JOB_NAMESPACE", "finops-demo")
JIRA_URL = os.environ.get("JIRA_URL", "")
JIRA_USER = os.environ.get("JIRA_USER", "")
JIRA_API_TOKEN = os.environ.get("JIRA_API_TOKEN", "")
JIRA_PROJECT_KEY = os.environ.get("JIRA_PROJECT_KEY", "")

pending_intents: dict[str, dict] = {}
processed: set[str] = set()

if SLACK_BOT_TOKEN and SLACK_SIGNING_SECRET:
    bolt_app = App(token=SLACK_BOT_TOKEN, signing_secret=SLACK_SIGNING_SECRET)
else:
    bolt_app = App(token="xoxb-placeholder", signing_secret="placeholder",
                   token_verification_enabled=False)
    log.warning("SLACK_BOT_TOKEN/SLACK_SIGNING_SECRET not set — Slack button verification disabled")

flask_app = Flask(__name__)
bolt_handler = SlackRequestHandler(bolt_app)


def _proposal_key(intent: dict) -> str:
    return f"{intent.get('cluster', '')}__{intent.get('namespace', '')}__{intent.get('workload', '')}"


def _parse_proposal_key(key: str) -> tuple[str, str, str]:
    parts = key.split("__", 2)
    if len(parts) == 3:
        return parts[0], parts[1], parts[2]
    return "", "", ""


def _sanitize_env_name(cluster: str) -> str:
    return re.sub(r"[^A-Z0-9]", "_", cluster.upper())


# ---------------------------------------------------------------------------
# Jira ticket integration
# ---------------------------------------------------------------------------

def _jira_auth() -> tuple[str, str]:
    return (JIRA_USER, JIRA_API_TOKEN)


def _create_jira_ticket(intent: dict) -> str | None:
    if not JIRA_URL or not JIRA_API_TOKEN:
        return None

    cluster = intent.get("cluster", "unknown")
    ns = intent.get("namespace", "")
    wl = intent.get("workload", "")
    saving = intent.get("monthly_saving_estimate", 0)
    cur = intent.get("current", {})
    rec = intent.get("recommended", {})

    summary = f"Right-size {wl} on {cluster} (save ${saving:.2f}/mo)"
    description = (
        f"*Cluster:* {cluster}\n"
        f"*Namespace:* {ns}\n"
        f"*Workload:* {wl}\n"
        f"*Current:* CPU {cur.get('cpu_request')}, Memory {cur.get('memory_request')}\n"
        f"*Recommended:* CPU {rec.get('cpu_request')}, Memory {rec.get('memory_request')}\n"
        f"*Estimated Saving:* ${saving:.2f}/mo\n\n"
        f"Generated by FinOps Autonomous Loop."
    )

    try:
        resp = httpx.post(
            f"{JIRA_URL}/rest/api/3/issue",
            auth=_jira_auth(),
            json={
                "fields": {
                    "project": {"key": JIRA_PROJECT_KEY},
                    "summary": summary,
                    "description": {
                        "version": 1,
                        "type": "doc",
                        "content": [{"type": "paragraph", "content": [{"type": "text", "text": description}]}],
                    },
                    "issuetype": {"name": "Task"},
                }
            },
            timeout=15,
        )
        resp.raise_for_status()
        key = resp.json().get("key", "")
        log.info("Created Jira ticket %s for %s/%s", key, ns, wl)
        return key
    except Exception as e:
        log.warning("Jira ticket creation failed: %s", e)
        return None


def _comment_jira_ticket(ticket_key: str, comment: str) -> None:
    if not ticket_key or not JIRA_URL:
        return
    try:
        httpx.post(
            f"{JIRA_URL}/rest/api/3/issue/{ticket_key}/comment",
            auth=_jira_auth(),
            json={"body": {"version": 1, "type": "doc", "content": [
                {"type": "paragraph", "content": [{"type": "text", "text": comment}]}
            ]}},
            timeout=15,
        )
        log.info("Updated Jira ticket %s", ticket_key)
    except Exception as e:
        log.warning("Jira comment failed: %s", e)


def _close_jira_ticket(ticket_key: str) -> None:
    if not ticket_key or not JIRA_URL:
        return
    try:
        resp = httpx.get(
            f"{JIRA_URL}/rest/api/3/issue/{ticket_key}/transitions",
            auth=_jira_auth(), timeout=15,
        )
        resp.raise_for_status()
        for t in resp.json().get("transitions", []):
            if t["name"].lower() in ("done", "closed", "resolve", "resolved"):
                httpx.post(
                    f"{JIRA_URL}/rest/api/3/issue/{ticket_key}/transitions",
                    auth=_jira_auth(),
                    json={"transition": {"id": t["id"]}},
                    timeout=15,
                )
                log.info("Closed Jira ticket %s", ticket_key)
                return
    except Exception as e:
        log.warning("Jira close failed: %s", e)


# ---------------------------------------------------------------------------
# AAP API integration
# ---------------------------------------------------------------------------

def _aap_headers() -> dict:
    return {"Authorization": f"Bearer {AAP_API_TOKEN}", "Content-Type": "application/json"}


def _find_pending_approval(workload: str, namespace: str) -> int | None:
    if not AAP_API_URL or not AAP_API_TOKEN:
        return None

    try:
        resp = httpx.get(
            f"{AAP_API_URL}/v2/workflow_approvals/?status=pending",
            headers=_aap_headers(), verify=False, timeout=15,
        )
        resp.raise_for_status()

        for approval in resp.json().get("results", []):
            source_wf = approval.get("summary_fields", {}).get("source_workflow_job", {})
            wf_job_id = source_wf.get("id")
            if not wf_job_id:
                continue

            job_resp = httpx.get(
                f"{AAP_API_URL}/v2/workflow_jobs/{wf_job_id}/",
                headers=_aap_headers(), verify=False, timeout=15,
            )
            job_resp.raise_for_status()
            extra_vars = job_resp.json().get("extra_vars", "{}")
            if isinstance(extra_vars, str):
                extra_vars = json.loads(extra_vars)

            if extra_vars.get("workload") == workload and extra_vars.get("namespace") == namespace:
                log.info("Found pending approval %d for %s/%s", approval["id"], namespace, workload)
                return approval["id"]

    except Exception as e:
        log.warning("AAP approval lookup failed: %s", e)

    return None


def _approve_aap_workflow(approval_id: int) -> tuple[int, str]:
    try:
        resp = httpx.post(
            f"{AAP_API_URL}/v2/workflow_approvals/{approval_id}/approve/",
            headers=_aap_headers(), verify=False, timeout=15,
        )
        resp.raise_for_status()
        log.info("AAP approval %d approved", approval_id)
        return 200, f"AAP workflow approved. Remediation running via AAP."
    except Exception as e:
        log.warning("AAP approve failed: %s", e)
        return 500, f"AAP approve failed: {e}"


def _deny_aap_workflow(approval_id: int) -> tuple[int, str]:
    try:
        resp = httpx.post(
            f"{AAP_API_URL}/v2/workflow_approvals/{approval_id}/deny/",
            headers=_aap_headers(), verify=False, timeout=15,
        )
        resp.raise_for_status()
        log.info("AAP approval %d denied", approval_id)
        return 200, f"AAP workflow denied."
    except Exception as e:
        log.warning("AAP deny failed: %s", e)
        return 500, f"AAP deny failed: {e}"


def _forward_to_aap_event_stream(intent: dict) -> None:
    if not AAP_EVENT_STREAM_URL:
        return
    auth = (AAP_EVENT_STREAM_USER, AAP_EVENT_STREAM_PASS) if AAP_EVENT_STREAM_USER else None
    try:
        httpx.post(AAP_EVENT_STREAM_URL, json=intent, auth=auth, verify=False, timeout=15)
        log.info("Forwarded intent to AAP Event Stream")
    except Exception as e:
        log.warning("AAP Event Stream POST failed: %s", e)


# ---------------------------------------------------------------------------
# K8s helpers — deny-path suppression + Actor Job creation (fallback)
# ---------------------------------------------------------------------------

def _get_k8s_apps_client(cluster: str):
    import kubernetes.client
    import kubernetes.config

    safe = _sanitize_env_name(cluster)
    host = os.environ.get(f"K8S_AUTH_HOST_{safe}", os.environ.get("K8S_AUTH_HOST", ""))
    token = os.environ.get(f"K8S_AUTH_API_KEY_{safe}", os.environ.get("K8S_AUTH_API_KEY", ""))

    if host and token:
        conf = kubernetes.client.Configuration()
        conf.host = host
        conf.verify_ssl = False
        api_client = kubernetes.client.ApiClient(conf)
        api_client.set_default_header("Authorization", f"Bearer {token}")
        return kubernetes.client.AppsV1Api(api_client)

    try:
        kubernetes.config.load_incluster_config()
        return kubernetes.client.AppsV1Api()
    except Exception:
        return None


def _suppress_workload(cluster: str, namespace: str, workload: str) -> bool:
    apps_api = _get_k8s_apps_client(cluster)
    if not apps_api:
        log.warning("No K8s client for cluster '%s' — suppression skipped", cluster)
        return False

    suppress_until = (datetime.now(timezone.utc) + timedelta(days=7)).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        apps_api.patch_namespaced_deployment(
            name=workload, namespace=namespace,
            body={"metadata": {"annotations": {
                "finops.redhat.com/suppressed-until": suppress_until,
                "finops.redhat.com/denied-by": "human",
                "finops.redhat.com/denied-at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            }}},
        )
        log.info("Suppressed %s/%s until %s", namespace, workload, suppress_until)
        return True
    except Exception as e:
        log.warning("Failed to annotate %s/%s: %s", namespace, workload, e)
        return False


def _create_actor_job(intent: dict) -> tuple[int, str]:
    import kubernetes.client
    import kubernetes.config

    cluster = intent.get("cluster", "")
    ns = intent.get("namespace", "")
    wl = intent.get("workload", "")
    container = intent.get("container", "")
    cur = intent.get("current", {})
    rec = intent.get("recommended", {})
    saving = intent.get("monthly_saving_estimate", 0)

    job_name = f"finops-actor-{wl}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"[:63]

    try:
        kubernetes.config.load_incluster_config()
        batch_api = kubernetes.client.BatchV1Api()
    except Exception as e:
        return 500, f"Cannot create Job (not in-cluster?): {e}"

    extra_vars = json.dumps({
        "cluster": cluster, "namespace": ns, "workload": wl, "container": container,
        "cpu_req": rec.get("cpu_request"), "mem_req": rec.get("memory_request"),
        "expected_cpu": cur.get("cpu_request"), "expected_mem": cur.get("memory_request"),
        "saving": str(saving), "slack_webhook_url": SLACK_WEBHOOK_URL,
    })

    job = kubernetes.client.V1Job(
        api_version="batch/v1", kind="Job",
        metadata=kubernetes.client.V1ObjectMeta(
            name=job_name, namespace=ACTOR_JOB_NAMESPACE,
            labels={"app": "finops-actor", "finops.redhat.com/workload": wl},
        ),
        spec=kubernetes.client.V1JobSpec(
            backoff_limit=0, ttl_seconds_after_finished=3600,
            template=kubernetes.client.V1PodTemplateSpec(
                spec=kubernetes.client.V1PodSpec(
                    service_account_name="finops-actor", restart_policy="Never",
                    containers=[kubernetes.client.V1Container(
                        name="actor", image=ACTOR_IMAGE,
                        command=["ansible-playbook", "playbooks/remediate-safe.yml", "-e", extra_vars],
                        env_from=[kubernetes.client.V1EnvFromSource(
                            secret_ref=kubernetes.client.V1SecretEnvSource(name="finops-cluster-tokens"))],
                        env=[kubernetes.client.V1EnvVar(name="SLACK_WEBHOOK_URL", value=SLACK_WEBHOOK_URL)],
                    )],
                ),
            ),
        ),
    )

    try:
        batch_api.create_namespaced_job(namespace=ACTOR_JOB_NAMESPACE, body=job)
        log.info("Created Actor Job '%s' for %s/%s", job_name, ns, wl)
        return 200, f"Approved: {ns}/{wl}. Actor Job '{job_name}' created."
    except Exception as e:
        log.warning("Failed to create Actor Job: %s", e)
        return 500, f"Failed to create Actor Job: {e}"


# ---------------------------------------------------------------------------
# Actions — approve / deny via AAP or fallback
# ---------------------------------------------------------------------------

def _handle_approve(cluster: str, namespace: str, workload: str) -> tuple[int, str]:
    key = f"{cluster}__{namespace}__{workload}"
    if key in processed:
        return 200, "Already processed."

    processed.add(key)

    if AAP_API_URL:
        approval_id = _find_pending_approval(workload, namespace)
        if approval_id:
            return _approve_aap_workflow(approval_id)
        log.warning("No pending AAP approval for %s/%s — falling back to direct Job", namespace, workload)

    intent = pending_intents.get(key)
    if intent:
        return _create_actor_job(intent)

    return 500, f"No pending intent found for {namespace}/{workload} and no AAP approval available."


def _handle_deny(cluster: str, namespace: str, workload: str) -> str:
    key = f"{cluster}__{namespace}__{workload}"
    if key in processed:
        return "Already processed."

    processed.add(key)

    if AAP_API_URL:
        approval_id = _find_pending_approval(workload, namespace)
        if approval_id:
            _deny_aap_workflow(approval_id)

    suppressed = _suppress_workload(cluster, namespace, workload)
    suffix = " Suppressed for 7 days." if suppressed else ""
    return f"Denied: {namespace}/{workload}.{suffix}"


# ---------------------------------------------------------------------------
# Slack Bolt action handlers
# ---------------------------------------------------------------------------

@bolt_app.action("finops_approve")
def handle_approve(ack, body, respond):
    ack()
    key = body["actions"][0]["value"]
    cluster, namespace, workload = _parse_proposal_key(key)

    if not namespace or not workload:
        respond(text=f"Invalid proposal key: {key}", replace_original=True)
        return

    log.info("Slack approve clicked: %s", key)
    intent = pending_intents.get(key, {})
    ticket_key = intent.get("jira_ticket", "")
    _comment_jira_ticket(ticket_key, f"Approved via Slack. Remediation triggered.")

    status, msg = _handle_approve(cluster, namespace, workload)
    pending_intents.pop(key, None)

    respond(
        text=f"Approved: {namespace}/{workload}. {msg}",
        replace_original=True,
    )


@bolt_app.action("finops_deny")
def handle_deny(ack, body, respond):
    ack()
    key = body["actions"][0]["value"]
    cluster, namespace, workload = _parse_proposal_key(key)

    if not namespace or not workload:
        respond(text=f"Invalid proposal key: {key}", replace_original=True)
        return

    log.info("Slack deny clicked: %s", key)
    intent = pending_intents.get(key, {})
    ticket_key = intent.get("jira_ticket", "")
    _comment_jira_ticket(ticket_key, f"Denied via Slack. Workload suppressed for 7 days.")
    _close_jira_ticket(ticket_key)

    msg = _handle_deny(cluster, namespace, workload)
    pending_intents.pop(key, None)

    respond(text=msg, replace_original=True)


# ---------------------------------------------------------------------------
# Flask routes
# ---------------------------------------------------------------------------

@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    return bolt_handler.handle(request)


@flask_app.route("/intent", methods=["POST"])
def receive_intent():
    body = request.get_json(force=True)

    if body.get("decision") != "approve":
        return jsonify({"status": f"Intent blocked by Observer: {body.get('reasons')}"}), 200

    key = _proposal_key(body)
    if key in processed:
        return jsonify({"status": f"Already processed: {key}"}), 200

    ticket_key = _create_jira_ticket(body)
    if ticket_key:
        body["jira_ticket"] = ticket_key
        body["jira_url"] = JIRA_URL

    pending_intents[key] = body
    _forward_to_aap_event_stream(body)
    log.info("Received intent: %s (ticket: %s)", key, ticket_key or "none")
    return jsonify({"status": f"Intent received: {key}", "jira_ticket": ticket_key}), 200


@flask_app.route("/health", methods=["GET"])
def health():
    return "ok", 200


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8085"))
    log.info("Approval server (Slack Bolt + Flask) starting on port %d", port)
    if AAP_API_URL:
        log.info("AAP integration enabled: %s", AAP_API_URL)
    else:
        log.info("AAP not configured — using direct Job creation fallback")
    flask_app.run(host="0.0.0.0", port=port)
